### ISSUE TITLE
All app starters BS fail to deploy on Cloud Foundry 

### ISSUE THREAD

**Issue by tzolov** [spring-cloud-stream-app-starters/core#102]
The upgrade to Boot from `2.1.3` to `2.1.6`, `Fishtown.SR2` and `Greenwich.SR2` is compulsory foor enabling the Prometheus RSocket Proxy micrometer (doesn't work for Boot versions below 2.1.5) but it seems to causes errors on CF environments (below). Looks like problem is with `spring-cloud-spring-service-connector-2.0.5.RELEASE.jar` derived from `spring-boot-2.1.6.jar`

Above changes don't cause issues on Local, minikube and GKE/k8s

This is the log from CF deploying `time` source BS: 
```
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] java.lang.NoClassDefFoundError: org/springframework/jdbc/datasource/DelegatingDataSource
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:61) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:24) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:288) ~[spring-cloud-connectors-core-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:180) ~[spring-cloud-connectors-core-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createService(AbstractCloudServiceConnectorFactory.java:105) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createInstance(AbstractCloudServiceConnectorFactory.java:99) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:142) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.afterPropertiesSet(AbstractCloudServiceConnectorFactory.java:94) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.config.CloudScanHelper.registerServiceBean(CloudScanHelper.java:93) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.config.CloudScanHelper.registerServiceBeans(CloudScanHelper.java:59) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.config.java.ServiceScanConfiguration.registerBeanDefinitions(ServiceScanConfiguration.java:22) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.config.java.CloudScanConfiguration.registerBeanDefinitions(CloudScanConfiguration.java:22) ~[spring-cloud-spring-service-connector-2.0.5.RELEASE.jar!/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:364) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:363) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.stream.app.time.source.rabbit.TimeSourceRabbitApplication.main(TimeSourceRabbitApplication.java:29) [classes/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [app/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [app/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.datasource.DelegatingDataSource
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_222]
2019-09-14T13:30:04.449+02:00 [APP/PROC/WEB/0] [OUT] ... 50 common frames omitted
```

**Comment by tzolov** [comment]
The root cause for this problem had nothing to do with the Apps but with the CF app deployment configuration.  

In particular the following Skipper property:
`SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_CLOUDFOUNDRY_ACCOUNTS[default]_DEPLOYMENT_SERVICES: mysql,rabbit`
was wrongly instructing the CF to bind the `mysql` service to the deployed App Starters. This expectedly triggered `java.lang.NoClassDefFoundError: org/springframework/jdbc/datasource/DelegatingDataSource` as the app starters don't use or configure DB in general. 
Removing the `mysql` service from the deployment property resolved the issue.

**Comment by aharonmu** [comment]
right....i have the same problem....but i do want all my stream app (except one) to use mysql.
is there a way to exclude one of the stream app to NOT use mysql?
